{
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;
    extraConfig = ''
# generated by home manager
    ${builtins.readFile ./hyprland.conf}
    '';
    systemd.enable = true;
  };
}
