[
  # █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
  # ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█
  "float, file_progress"
  "float, confirm"
  "float, dialog"
  "float, download"
  "float, polkit-kde-authentication-agent-1"
  "float, notification"
  "float, error"
  "float, splash"
  "float, confirmreset"
  "float, title:Open File"
  "float, title:branchdialog"
  "float, Lxappearance"
  "float, Rofi"
  "animation none,Rofi"
  "float,viewnior"
  "float,feh"
  "float, pavucontrol-qt"
  "float, pavucontrol"
  "float, file-roller"
  "fullscreen, wlogout"
  "float, title:wlogout"
  "fullscreen, title:wlogout"
  "idleinhibit focus, mpv"
  "idleinhibit fullscreen, firefox"
  "float, title:^(Media viewer)$"
  "float, title:^(Volume Control)$"
  "float, title:^(Picture-in-Picture)$"
  "size 800 600, title:^(Volume Control)$"
  "move 75 44%, title:^(Volume Control)$"
]
