{
  wayland.windowManager.hyprland = {
    # Whether to enable Hyprland wayland compositor
    enable = true;
    # Whether to enable XWayland
    xwayland.enable = true;
    # Optional
    # Whether to enable hyprland-session.target on hyprland startup
    extraConfig = ''
# generated by home manager
    ${builtins.readFile ./hyprland.conf}
    '';
    systemd.enable = true;
  };
}
